#!/bin/bash

set -e

export CF_DIR=/var/vcap/cf
export CF_DOMAIN=v3.pcfdev.io
export CF_ORG=cfdev-org
export CF_SPACE=cfdev-space
export HOST_IP="${HOST_IP:-192.168.65.1}"
export DOCKER_REGISTRIES="${DOCKER_REGISTRIES:-[\"host.pcfdev.io:5000\"]}"

mkdir -p "${CF_DIR}"

exec 1> >(tee -i "${CF_DIR}/deploy.log")
exec 2>&1

source /var/vcap/director/env

cp /etc/cf/deployment.yml "${CF_DIR}"

for file_path in /var/vcap/cache/*; do
  file_name=$(basename $file_path)
  sed -i "s~url:.*$file_name~url: file://$file_path~g"  "${CF_DIR}/deployment.yml"
done

bosh -n update-cloud-config \
	/etc/cf/cloud-config.yml

stemcell_version=$(bosh interpolate /etc/cf/deployment.yml --path /stemcells/0/version)

bosh --tty upload-stemcell \
      "/var/vcap/cache/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=$stemcell_version"

bosh --tty --non-interactive --deployment cf \
  deploy "${CF_DIR}/deployment.yml" \
  -v system_domain="${CF_DOMAIN}" \
  -v host_ip="${HOST_IP}" \
  -v insecure_docker_registries="${DOCKER_REGISTRIES}" \
  --no-redact \
  --vars-store "${CF_DIR}/vars.yml"

#bosh run-errand local-volume-broker-registrar -d cf --keep-alive

org=cfdev-org
space=cfdev-space

cf api "api.${CF_DOMAIN}" --skip-ssl-validation
cf auth admin admin
cf enable-feature-flag diego_docker

cf create-user user pass
cf create-org "${CF_ORG}"
cf create-space "${CF_SPACE}" -o "${CF_ORG}"

cf set-org-role user "${CF_ORG}" OrgManager
cf set-space-role user "${CF_ORG}" "${CF_SPACE}" SpaceManager
cf set-space-role user "${CF_ORG}" "${CF_SPACE}" SpaceDeveloper
cf set-space-role user "${CF_ORG}" "${CF_SPACE}" SpaceAuditor

cf create-security-group all_access /etc/cf/app-security-group.json
cf bind-staging-security-group all_access
cf bind-running-security-group all_access
