// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdevd/cmd (interfaces: DaemonRunner)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDaemonRunner is a mock of DaemonRunner interface
type MockDaemonRunner struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonRunnerMockRecorder
}

// MockDaemonRunnerMockRecorder is the mock recorder for MockDaemonRunner
type MockDaemonRunnerMockRecorder struct {
	mock *MockDaemonRunner
}

// NewMockDaemonRunner creates a new mock instance
func NewMockDaemonRunner(ctrl *gomock.Controller) *MockDaemonRunner {
	mock := &MockDaemonRunner{ctrl: ctrl}
	mock.recorder = &MockDaemonRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDaemonRunner) EXPECT() *MockDaemonRunnerMockRecorder {
	return m.recorder
}

// RemoveDaemon mocks base method
func (m *MockDaemonRunner) RemoveDaemon(arg0 string) error {
	ret := m.ctrl.Call(m, "RemoveDaemon", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDaemon indicates an expected call of RemoveDaemon
func (mr *MockDaemonRunnerMockRecorder) RemoveDaemon(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDaemon", reflect.TypeOf((*MockDaemonRunner)(nil).RemoveDaemon), arg0)
}
