#!/bin/sh

set -e

DIRECTOR_IP=${1-"10.245.0.2"}
BOSH_LITE_SUBNET=${2-"10.244.0.0/16"}
DIRECTOR_PORT=${3-25555}

mkdir -p /var/vcap/director

inotifywait -m -e create --format "%f" /var/vcap/director | while read FILENAME
do

if [ "${FILENAME}" == "trigger-route-setup" ]; then
    echo "BOSH Director is up - adding the iptable route for ${BOSH_LITE_SUBNET}"
    ip route add "${BOSH_LITE_SUBNET}" via "${DIRECTOR_IP}"
    kill TERM -- -$$
fi

done
