// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdev/cmd/stop (interfaces: LinuxKit)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLinuxKit is a mock of LinuxKit interface
type MockLinuxKit struct {
	ctrl     *gomock.Controller
	recorder *MockLinuxKitMockRecorder
}

// MockLinuxKitMockRecorder is the mock recorder for MockLinuxKit
type MockLinuxKitMockRecorder struct {
	mock *MockLinuxKit
}

// NewMockLinuxKit creates a new mock instance
func NewMockLinuxKit(ctrl *gomock.Controller) *MockLinuxKit {
	mock := &MockLinuxKit{ctrl: ctrl}
	mock.recorder = &MockLinuxKitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLinuxKit) EXPECT() *MockLinuxKitMockRecorder {
	return m.recorder
}

// Destroy mocks base method
func (m *MockLinuxKit) Destroy() error {
	ret := m.ctrl.Call(m, "Destroy")
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy
func (mr *MockLinuxKitMockRecorder) Destroy() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockLinuxKit)(nil).Destroy))
}

// Stop mocks base method
func (m *MockLinuxKit) Stop() error {
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop
func (mr *MockLinuxKitMockRecorder) Stop() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockLinuxKit)(nil).Stop))
}
