// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdev/cmd/start (interfaces: MetaDataReader)

// Package mocks is a generated GoMock package.
package mocks

import (
	workspace "code.cloudfoundry.org/cfdev/workspace"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMetaDataReader is a mock of MetaDataReader interface
type MockMetaDataReader struct {
	ctrl     *gomock.Controller
	recorder *MockMetaDataReaderMockRecorder
}

// MockMetaDataReaderMockRecorder is the mock recorder for MockMetaDataReader
type MockMetaDataReaderMockRecorder struct {
	mock *MockMetaDataReader
}

// NewMockMetaDataReader creates a new mock instance
func NewMockMetaDataReader(ctrl *gomock.Controller) *MockMetaDataReader {
	mock := &MockMetaDataReader{ctrl: ctrl}
	mock.recorder = &MockMetaDataReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetaDataReader) EXPECT() *MockMetaDataReaderMockRecorder {
	return m.recorder
}

// Metadata mocks base method
func (m *MockMetaDataReader) Metadata() (workspace.Metadata, error) {
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(workspace.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata
func (mr *MockMetaDataReaderMockRecorder) Metadata() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockMetaDataReader)(nil).Metadata))
}
