#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."
mkdir -p output/cache/{bin,releases}
rm -f output/cache/*.yml output/generate.log

rq -y < ../cf-deployment/cf-deployment.yml | jq -r '.stemcells[0].version' > output/STEMCELL.txt

echo "GENERATE MANIFESTS"
./scripts/generate-bosh-manifest -b ../bosh-deployment/ 2>> output/generate.log
./scripts/generate-cf-manifest -c ../cf-deployment/ 2>> output/generate.log
./scripts/generate-cf-mysql-manifest -m ../cf-mysql-deployment/ 2>> output/generate.log
./scripts/build-workspace-tar 2>> output/generate.log >> output/generate.log

echo "MODIFY MANIFESTS"
go run src/builder/main.go $(cat output/STEMCELL.txt) output/cache/*.yml

echo "DELETE OLD FILES"
find output/cache/ -type f ! -newer output/STEMCELL.txt -delete

echo "MAKE ISO FILE"
mkisofs -quiet -V cf-deps -R -o output/cf-deps.iso output/cache/
