#!/usr/bin/env bash

set -ex
cd "$(dirname "$0")/.."

rm -rf output
mkdir output

./scripts/generate-cf-manifest -c ../cf-deployment
./scripts/generate-bosh-manifest -b ../bosh-deployment/
./scripts/generate-cloud-config -c ../cf-deployment/
./scripts/build-cf-deps-tar -m output/cf.yml -c output/cloud-config.yml
./scripts/build-cf-deps-iso -c output/cf.tgz -b output/bosh.tgz
./scripts/build-image -l ~/.cfdev/cache/linuxkit
./scripts/run_hyperkit -i output/cfdev-efi.iso -c output/cf-oss-deps.iso
