#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."
iso_dir="$PWD"/output/cache

./images/cf/build.sh

# Place the 'workspace' container image
cid=$(docker run -d pivotal/cf sleep infinity)
docker export "$cid" > "${iso_dir}/workspace.tar"
docker kill "$cid"
docker rm "$cid"
