#!/usr/bin/env bash

set -ex

while getopts "c:b:m:" arg; do
  case $arg in
    c) cf_deps=$OPTARG
      ;;
    m) mysql_deps=$OPTARG
      ;;
    b) bosh_deps=$OPTARG
  esac
done

if [[ -z "$cf_deps" || -z "$mysql_deps" || -z "$bosh_deps" ]]; then
  echo "USAGE: ./build-cf-iso -c <cf-deps-tar> -m <cf-mysql-deps-tar> -b <bosh-deps-tar>"
  exit 1
fi
if [[ ! -f $cf_deps || ! -f $mysql_deps || ! -f $bosh_deps ]]; then
  echo "ERROR: Either $cf_deps, $mysql_deps or $bosh_deps do not exist"
  exit 2
fi
cf_deps="$(cd "$(dirname "$cf_deps")"; pwd)/$(basename "$cf_deps")"
mysql_deps="$(cd "$(dirname "$mysql_deps")"; pwd)/$(basename "$mysql_deps")"
bosh_deps="$(cd "$(dirname "$bosh_deps")"; pwd)/$(basename "$bosh_deps")"

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
output_dir="$script_dir/../output"
iso_file="$output_dir"/cf-deps.iso

rm -rf "$iso_file"
mkdir -p "$output_dir"
iso_dir="$(mktemp -d)"
trap cleanup EXIT


cleanup() {
  rm -rf "$iso_dir"
}

build() {
  "$script_dir"/../images/cf/build.sh
}


export() {
  # Place the 'workspace' container image
  cid=$(docker run -d pivotal/cf sleep infinity)
  docker export "$cid" > "${iso_dir}/workspace.tar"
  docker kill "$cid"
  docker rm "$cid"
}

add_deps(){
  tar xzf "$cf_deps" -C $iso_dir
  tar xzf "$mysql_deps" -C $iso_dir
  tar xzf "$bosh_deps" -C $iso_dir
}

make_iso() {
  mkisofs -V cf-deps -R -o "$iso_file" "$iso_dir"
}

main () {
  build
  export
  add_deps
  make_iso
}

main
