#!/usr/bin/env bash

set -ex

while getopts "m:" arg; do
  case $arg in
    m) manifest="$OPTARG"
      ;;
  esac
done

if [[ -z $manifest ]]; then
  echo "USAGE: build-cf-deps-tar -m <path-to-cf-mysql-manifest>"
  exit 2
fi
if [[ ! -f $manifest ]]; then
  echo "ERROR: $manifest does not exist"
  exit 2
fi
manifest="$(cd "$(dirname "$manifest")"; pwd)/$(basename "$manifest")"

if [[ -z "$BOSH_ENVIRONMENT" ]]; then
  echo "ERROR: a bosh director is required to compile releases, please set your BOSH_* env variables"
  exit 3
fi

dir="$(cd "$( dirname $0)" && pwd)"
output_dir="$dir"/../output
tmpdir="$(mktemp -d)"
mkdir -p "$output_dir"
mkdir -p "$tmpdir"/releases
trap cleanup EXIT

source "$dir"/build-deps-tar-helpers

tar_deps () {
  cp "$manifest" "$tmpdir"/mysql.yml
  pushd "$tmpdir"
    tar cvzf "$output_dir"/mysql.tgz *
  popd
}

main () {
  download_warden_stemcell
  download_compiled_releases
  compile_releases "$manifest"
  tar_deps
}

main
