#!/usr/bin/env bash

set -ex

while getopts "m:c:r:" arg; do
  case $arg in
    m) manifest="$OPTARG"
      ;;
    r) runtime="$OPTARG"
      ;;
    c) cloud_config="$OPTARG"
  esac
done

if [[ -z $manifest || -z $cloud_config || -z $runtime ]]; then
  echo "USAGE: build-cf-deps-tar -m <path-to-cf-manifest> -c <path-to-cloud-config> -r <path-to-runtime-config>"
  exit 2
fi
if [[ ! -f $manifest || ! -f $cloud_config  || ! -f $runtime ]]; then
  echo "ERROR: Either $manifest of $cloud_config do not exist"
  exit 2
fi
manifest="$(cd "$(dirname "$manifest")"; pwd)/$(basename "$manifest")"
cloud_config="$(cd "$(dirname "$cloud_config")"; pwd)/$(basename "$cloud_config")"
runtime_config="$(cd "$(dirname "$runtime")"; pwd)/$(basename "$runtime")"

if [[ -z "$BOSH_ENVIRONMENT" ]]; then
  echo "ERROR: a bosh director is required to compile releases, please set your BOSH_* env variables"
  exit 3
fi

dir="$(cd "$( dirname $0)" && pwd)"
output_dir="$dir"/../output
tmpdir="$(mktemp -d)"
mkdir -p "$output_dir"
mkdir -p "$tmpdir"/releases
trap cleanup EXIT

cleanup () {
  rm -rf "$tmpdir"
}

stemcell_version () {
  rq -y <"$manifest" | jq -r '.stemcells[0].version'
}

name () {
  echo "$1" | jq -r .name
}

url () {
  echo "$1" | jq -r .url
}

version () {
  echo "$1" | jq -r .version
}

filename () {
  echo "$(name "$1")-$(version "$1")-ubuntu-trusty-$(stemcell_version).tgz"
}


download_warden_stemcell () {
  pushd "$tmpdir"
    wget "https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-$(stemcell_version)-warden-boshlite-ubuntu-trusty-go_agent.tgz"
  popd
}

download_compiled_releases () {
  compiled_releases="$(rq -y <"$manifest" | jq -c '.releases[] | select(has("stemcell"))')"
  for release in $compiled_releases; do
    wget "$(url "$release")" -O "$tmpdir"/releases/"$(filename "$release")"
  done
}

compilation_manifest_template="$(cat <<EOF
---
instance_groups: []
name: cf
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "$(stemcell_version)"
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  update_watch_time: 5000-1200000
EOF
)"

compile_releases () {
    releases_to_compile="$(rq -y <"$1" | jq -c '[.releases[] | select(has("stemcell") | not)]')"
    compilation_manifest="$(echo "$compilation_manifest_template" | rq -y | jq ".releases=$releases_to_compile" | rq -Y)"
    bosh upload-stemcell "https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-$(stemcell_version)-google-kvm-ubuntu-trusty-go_agent.tgz"
    bosh -n deploy -d cf <(echo "$compilation_manifest")
    for release in $(echo $releases_to_compile | jq -c .[]) ; do
        bosh -d cf export-release "$(name "$release")/$(version "$release")" ubuntu-trusty/"$(stemcell_version)" --dir "$tmpdir"
        mv "$tmpdir"/"$(name "$release")-$(version "$release")"-*.tgz "$tmpdir"/"$(filename $release)"
    done
}

tar_deps () {
  cp "$manifest" "$tmpdir"/deployment.yml
  cp "$cloud_config" "$tmpdir"/cloud-config.yml
  cp "$runtime" "$tmpdir"/runtime-config.yml
  pushd "$tmpdir"
    tar cvzf "$output_dir"/cf.tgz *
  popd
}

main () {
  download_warden_stemcell
  download_compiled_releases
  compile_releases "$manifest"
  compile_releases "$runtime"
  tar_deps
}

main
