#!/bin/bash -e
set -euxo pipefail

while getopts "l:o:" arg; do
  case $arg in
    l) linuxkit=$OPTARG
      ;;
    o) os=$OPTARG
      ;;
  esac
done

if [[ -z ${linuxkit:-} ]]; then
  if ! which linuxkit; then
    echo "ERROR: either provide the linuxkit binary with the '-l' flag or add linuxkit to your path"
    exit 1
  else
    linuxkit="linuxkit"
  fi
fi

if [[ -z $os ]]; then
  os=darwin
fi

script_dir="$( cd "$( dirname "$BASH_SOURCE[0]" )" && pwd )"
output_dir="$script_dir"/../output
linuxkit_dir="$script_dir"/../linuxkit

if [[ "$os" == "windows" ]]; then
  baseyml_path="$linuxkit_dir"/base-windows.yml
else
  baseyml_path="$linuxkit_dir"/base.yml
fi

mkdir -p "$output_dir"

"$linuxkit" pkg build -hash dev "$linuxkit_dir"/pkg/bosh-lite-routing
"$linuxkit" pkg build -hash dev "$linuxkit_dir"/pkg/expose-multiple-ports
"$linuxkit" pkg build -hash dev "$linuxkit_dir"/pkg/garden-runc
"$linuxkit" pkg build -hash dev "$linuxkit_dir"/pkg/openssl

"$linuxkit" build \
 -disable-content-trust \
 -name cfdev \
 -format iso-efi \
 -dir "$output_dir" \
 $baseyml_path \
 "$linuxkit_dir"/garden.yml \
