#!/usr/bin/env bash

set -ex

while getopts "b:cu" arg; do
  case $arg in
    b) bosh_deployment=$OPTARG
      ;;
    c) include_credhub=true
      ;;
    u) include_uaa=true
      ;;
  esac
done

if [[ -z $bosh_deployment ]]; then
  echo "USAGE: generate-bosh-manifest -b <path-to-bosh-deployment>"
  exit 1
fi
if [[ ! -d $bosh_deployment ]]; then
  echo "ERROR: bosh_deployment $bosh_deployment does not exist"
  exit 2
fi
bosh_deployment="$(cd "$(dirname "$bosh_deployment")"; pwd)/$(basename "$bosh_deployment")"

scripts_dir="$(cd "$(dirname "$0")" && pwd)"
output_dir="$scripts_dir"/../output
ops_dir="$scripts_dir"/../images/cf/bosh-operations
mkdir -p "$output_dir"

pushd "$bosh_deployment"
    bosh int runtime-configs/dns.yml \
      -o "$ops_dir"/add-host-pcfdev-dns-record.yml \
      \
      > "$output_dir/dns-runtime-config.yml"
popd
