#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")"/.. && pwd)"
output_dir="$root_dir"/output/cache
imgscf_dir="$root_dir"/images/cf
ops_dir="$root_dir"/images/cf/mysql-operations
while getopts "m:s:" arg; do
  case $arg in
    m) cf_mysql_deployment="$(cd $OPTARG && pwd)"
      ;;
    s) stemcell_version=$OPTARG
      ;;
  esac
done
for var in cf_mysql_deployment stemcell_version; do
  if [[ -z ${!var:-} ]]; then
    echo "USAGE: generate-cf-mysql-manifest -m <path-to-cf-mysql-deployment> -s <stemcell_version>"
    exit 1
  fi
done
set -x

cp "$imgscf_dir"/deploy-mysql "$output_dir"/bin/deploy-mysql

stemcell_ops="---
- type: replace
  path: /stemcells/alias=default/version
  value: "$stemcell_version"
"

pushd "$cf_mysql_deployment"
  bosh int cf-mysql-deployment.yml \
    -o operations/add-broker.yml \
    -o operations/register-proxy-route.yml \
    -o operations/no-arbitrator.yml \
    \
    -o "$ops_dir"/single-instances.yml \
    -o <(echo "$stemcell_ops") \
    \
    -v cf_mysql_external_host=p-mysql.v3.pcfdev.io \
    -v cf_mysql_host=v3.pcfdev.io \
    -v cf_admin_password=admin \
    -v cf_api_url=https://api.v3.pcfdev.io \
    -v cf_skip_ssl_validation=true \
    -v proxy_vm_extension=mysql-proxy-lb \
    \
    > "$output_dir/mysql.yml"
popd
