// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdev/cmd/start (interfaces: SystemProfiler)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSystemProfiler is a mock of SystemProfiler interface
type MockSystemProfiler struct {
	ctrl     *gomock.Controller
	recorder *MockSystemProfilerMockRecorder
}

// MockSystemProfilerMockRecorder is the mock recorder for MockSystemProfiler
type MockSystemProfilerMockRecorder struct {
	mock *MockSystemProfiler
}

// NewMockSystemProfiler creates a new mock instance
func NewMockSystemProfiler(ctrl *gomock.Controller) *MockSystemProfiler {
	mock := &MockSystemProfiler{ctrl: ctrl}
	mock.recorder = &MockSystemProfilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSystemProfiler) EXPECT() *MockSystemProfilerMockRecorder {
	return m.recorder
}

// GetAvailableMemory mocks base method
func (m *MockSystemProfiler) GetAvailableMemory() (uint64, error) {
	ret := m.ctrl.Call(m, "GetAvailableMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableMemory indicates an expected call of GetAvailableMemory
func (mr *MockSystemProfilerMockRecorder) GetAvailableMemory() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableMemory", reflect.TypeOf((*MockSystemProfiler)(nil).GetAvailableMemory))
}

// GetTotalMemory mocks base method
func (m *MockSystemProfiler) GetTotalMemory() (uint64, error) {
	ret := m.ctrl.Call(m, "GetTotalMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalMemory indicates an expected call of GetTotalMemory
func (mr *MockSystemProfilerMockRecorder) GetTotalMemory() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalMemory", reflect.TypeOf((*MockSystemProfiler)(nil).GetTotalMemory))
}
