// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdev/cmd/start (interfaces: Toggle)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockToggle is a mock of Toggle interface
type MockToggle struct {
	ctrl     *gomock.Controller
	recorder *MockToggleMockRecorder
}

// MockToggleMockRecorder is the mock recorder for MockToggle
type MockToggleMockRecorder struct {
	mock *MockToggle
}

// NewMockToggle creates a new mock instance
func NewMockToggle(ctrl *gomock.Controller) *MockToggle {
	mock := &MockToggle{ctrl: ctrl}
	mock.recorder = &MockToggleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockToggle) EXPECT() *MockToggleMockRecorder {
	return m.recorder
}

// Enabled mocks base method
func (m *MockToggle) Enabled() bool {
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled
func (mr *MockToggleMockRecorder) Enabled() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockToggle)(nil).Enabled))
}

// SetCFAnalyticsEnabled mocks base method
func (m *MockToggle) SetCFAnalyticsEnabled(arg0 bool) error {
	ret := m.ctrl.Call(m, "SetCFAnalyticsEnabled", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCFAnalyticsEnabled indicates an expected call of SetCFAnalyticsEnabled
func (mr *MockToggleMockRecorder) SetCFAnalyticsEnabled(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCFAnalyticsEnabled", reflect.TypeOf((*MockToggle)(nil).SetCFAnalyticsEnabled), arg0)
}

// SetCustomAnalyticsEnabled mocks base method
func (m *MockToggle) SetCustomAnalyticsEnabled(arg0 bool) error {
	ret := m.ctrl.Call(m, "SetCustomAnalyticsEnabled", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCustomAnalyticsEnabled indicates an expected call of SetCustomAnalyticsEnabled
func (mr *MockToggleMockRecorder) SetCustomAnalyticsEnabled(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCustomAnalyticsEnabled", reflect.TypeOf((*MockToggle)(nil).SetCustomAnalyticsEnabled), arg0)
}

// SetProp mocks base method
func (m *MockToggle) SetProp(arg0, arg1 string) error {
	ret := m.ctrl.Call(m, "SetProp", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProp indicates an expected call of SetProp
func (mr *MockToggleMockRecorder) SetProp(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProp", reflect.TypeOf((*MockToggle)(nil).SetProp), arg0, arg1)
}
